name             'git'
maintainer       'a-know'
license          'All rights reserved'
description      'Installs/Configures git'
long_description 'ditto' # IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'gettext-devel'
depends          'openssl-devel'
depends          'expat-devel'
depends          'perl-extutils'
depends          'curl-devel'
depends          'zlib'
